Update eslint config
gromcode/react-init pull request #10
Opened 2021-10-08 11:54 UTC by DvijIt

2021-11-01 17:05 UTC, andrii142 requested changes

2021-11-01 17:05 UTC, andrii142 commented on .eslintrc.js
> +      version: '16.14',
why should we fix version here?

2021-11-01 17:05 UTC, andrii142 commented on task/src/App.jsx
> +import React from "react";
must be reverted

2021-11-02 07:58 UTC, DvijIt commented on task/src/App.jsx
> +import React from "react";
reverted

2021-11-02 07:58 UTC, DvijIt commented on .eslintrc.js
> +      version: '16.14',
change to detect

2021-11-02 11:18 UTC, merged